project_id = "twjtchqgnnadfjjcftqv"

[functions.create-staff-user]
verify_jwt = false

[functions.admin-change-password]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.reset-database]
verify_jwt = false
